
package com.bosorio.instagram.dev.wsdl.post;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PostServiceImplService", targetNamespace = "http://services.dev.instagram.bosorio.org/", wsdlLocation = "http://localhost:8080/instagram-dev-backend/PostServiceImpl?wsdl")
public class PostServiceImplService
    extends Service
{

    private static final URL POSTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException POSTSERVICEIMPLSERVICE_EXCEPTION;
    private static final QName POSTSERVICEIMPLSERVICE_QNAME = new QName("http://services.dev.instagram.bosorio.org/", "PostServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/instagram-dev-backend/PostServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        POSTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PostServiceImplService() {
        super(__getWsdlLocation(), POSTSERVICEIMPLSERVICE_QNAME);
    }

    public PostServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTSERVICEIMPLSERVICE_QNAME, features);
    }

    public PostServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, POSTSERVICEIMPLSERVICE_QNAME);
    }

    public PostServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTSERVICEIMPLSERVICE_QNAME, features);
    }

    public PostServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostService
     */
    @WebEndpoint(name = "PostServiceImplPort")
    public PostService getPostServiceImplPort() {
        return super.getPort(new QName("http://services.dev.instagram.bosorio.org/", "PostServiceImplPort"), PostService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostService
     */
    @WebEndpoint(name = "PostServiceImplPort")
    public PostService getPostServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.dev.instagram.bosorio.org/", "PostServiceImplPort"), PostService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw POSTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return POSTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
