
package com.bosorio.instagram.dev.wsdl.post;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PostService", targetNamespace = "http://services.dev.instagram.bosorio.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostService {


    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.util.List<com.bosorio.instagram.dev.wsdl.post.PostUser>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFollowingPosts", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindFollowingPosts")
    @ResponseWrapper(localName = "findFollowingPostsResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindFollowingPostsResponse")
    public List<PostUser> findFollowingPosts(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        Post arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        Post arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.bosorio.instagram.dev.wsdl.post.Post
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindByIdResponse")
    public Post findById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.util.List<com.bosorio.instagram.dev.wsdl.post.Post>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserPosts", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindUserPosts")
    @ResponseWrapper(localName = "findUserPostsResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindUserPostsResponse")
    public List<Post> findUserPosts(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
