
package com.bosorio.instagram.dev.wsdl.post;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://services.dev.instagram.bosorio.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "unfollow", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Unfollow")
    @ResponseWrapper(localName = "unfollowResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.UnfollowResponse")
    public void unfollow(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "follow", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Follow")
    @ResponseWrapper(localName = "followResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FollowResponse")
    public void follow(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.LoginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.bosorio.instagram.dev.wsdl.post.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindAllResponse")
    public List<User> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.CreateResponse")
    public String create(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.bosorio.instagram.dev.wsdl.post.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindByIdResponse")
    public User findById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bosorio.instagram.dev.wsdl.post.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFollowing", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindFollowing")
    @ResponseWrapper(localName = "findFollowingResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindFollowingResponse")
    public List<User> findFollowing(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.bosorio.instagram.dev.wsdl.post.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByUsername", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindByUsername")
    @ResponseWrapper(localName = "findByUsernameResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindByUsernameResponse")
    public User findByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bosorio.instagram.dev.wsdl.post.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFollowers", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindFollowers")
    @ResponseWrapper(localName = "findFollowersResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.post.FindFollowersResponse")
    public List<User> findFollowers(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
