
package com.bosorio.instagram.dev.wsdl.comment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CommentServiceImplService", targetNamespace = "http://services.dev.instagram.bosorio.org/", wsdlLocation = "http://localhost:8080/instagram-dev-backend/CommentServiceImpl?wsdl")
public class CommentServiceImplService
    extends Service
{

    private static final URL COMMENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException COMMENTSERVICEIMPLSERVICE_EXCEPTION;
    private static final QName COMMENTSERVICEIMPLSERVICE_QNAME = new QName("http://services.dev.instagram.bosorio.org/", "CommentServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/instagram-dev-backend/CommentServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMENTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COMMENTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CommentServiceImplService() {
        super(__getWsdlLocation(), COMMENTSERVICEIMPLSERVICE_QNAME);
    }

    public CommentServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMENTSERVICEIMPLSERVICE_QNAME, features);
    }

    public CommentServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, COMMENTSERVICEIMPLSERVICE_QNAME);
    }

    public CommentServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMENTSERVICEIMPLSERVICE_QNAME, features);
    }

    public CommentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommentServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommentService
     */
    @WebEndpoint(name = "CommentServiceImplPort")
    public CommentService getCommentServiceImplPort() {
        return super.getPort(new QName("http://services.dev.instagram.bosorio.org/", "CommentServiceImplPort"), CommentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommentService
     */
    @WebEndpoint(name = "CommentServiceImplPort")
    public CommentService getCommentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.dev.instagram.bosorio.org/", "CommentServiceImplPort"), CommentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMENTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw COMMENTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return COMMENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
