
package com.bosorio.instagram.dev.wsdl.comment;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CommentService", targetNamespace = "http://services.dev.instagram.bosorio.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommentService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.bosorio.instagram.dev.wsdl.comment.Comment
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.FindByIdResponse")
    public Comment findById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bosorio.instagram.dev.wsdl.comment.PostComment>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPostComments", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.FindPostComments")
    @ResponseWrapper(localName = "findPostCommentsResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.FindPostCommentsResponse")
    public List<PostComment> findPostComments(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        Comment arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://services.dev.instagram.bosorio.org/", className = "com.bosorio.instagram.dev.wsdl.comment.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        Comment arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
